# Processing results from different VLMs

In [18]:
#imports
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from scipy import stats
#remove warnings
import warnings
warnings.filterwarnings('ignore')

## Local VLMs for scenario prediction (from frames)

In [19]:
# Load and process VLM frame prediction results
def load_results(directory):
    results = pd.DataFrame()
    full_results_mode = pd.DataFrame()
    full_results_last = pd.DataFrame()
    
    for filename in os.listdir(directory):
        if filename.startswith('results_'):
            filepath = os.path.join(directory, filename)
            df = pd.read_csv(filepath)
            
            # Extract model name and dataset type from filename
            # Format: results_modelname_Xs.csv (e.g., results_gemma3_1s.csv)
            base_name = filename[8:-4]  # Remove 'results_' and '.csv'
            
            # Split by underscore and check if last part is dataset duration (1s, 3s, etc.)
            parts = base_name.split('_')
            if len(parts) >= 2 and parts[-1].endswith('s') and parts[-1][:-1].isdigit():
                # Last part is duration (1s, 3s, etc.)
                dataset_duration = parts[-1]
                model_base_name = '_'.join(parts[:-1])
                model_name = f"{model_base_name}_{dataset_duration}"
            else:
                # Fallback: use full base name
                model_name = base_name
                dataset_duration = "unknown"
            
            df['model'] = model_name
            df['dataset_duration'] = dataset_duration
            
            print(f'Loading {filename}')
            print(f'  Model: {model_name}')
            print(f'  Dataset duration: {dataset_duration}')
            print(f'  Rows: {len(df)}')
            
            # Make model first column
            df = df[['model', 'dataset_duration'] + [col for col in df.columns if col not in ['model', 'dataset_duration']]]
            
            # Clean and validate outcome predictions
            df['outcome_prediction'] = df['outcome_prediction'].astype(str).str.strip().str.lower()
            df['outcome_prediction'] = df['outcome_prediction'].str.replace(r'[^\w\s]', '', regex=True)
            
            # Filter for valid predictions only
            # Accept 'well' or 'poorly', tolerate case and optional trailing period
            cleaned_pred = df['outcome_prediction'].astype(str).str.strip().str.lower().str.rstrip('.')
            # check if prediction contains word well or poorly
            # Accept predictions that contain 'well' or 'poorly' as whole words
            valid_predictions = cleaned_pred.str.contains(r'\b(well|poorly)\b', na=False)
            # Normalize stored prediction to the matched token ('well' or 'poorly')
            df.loc[valid_predictions, 'outcome_prediction'] = cleaned_pred[valid_predictions].str.extract(r'\b(well|poorly)\b', expand=False)
            # Ensure mask excludes any rows where extraction failed
            valid_predictions = valid_predictions & df['outcome_prediction'].notna()

            
            #########valid_predictions = cleaned_pred.isin(['well', 'poorly'])
            #print if not
            for pred in df['outcome_prediction'][~valid_predictions].unique():
                print(f'  Invalid prediction found: "{pred}"')
            df_clean = df[valid_predictions].copy()
            
            print(f'  Valid predictions: {len(df_clean)}/{len(df)} ({len(df_clean)/len(df)*100:.1f}%)')
            
            if df_clean.empty:
                print(f'  No valid predictions found in {filename}')
                continue
            
            # Extract video name from frame filename
            # Expected format: q_X_main_Y_30fps_frameZZZZ.png -> q_X
            def extract_video_name(frame_file):
                try:
                    # Remove .png extension and extract video ID
                    base_name = frame_file.replace('.png', '')
                    # Split by underscore and take first two parts (q_X)
                    parts = base_name.split('_')
                    if len(parts) >= 2:
                        video_id = f"{parts[0]}_{parts[1]}"  # e.g., "q_10"
                        return video_id
                    return frame_file  # fallback
                except:
                    return frame_file  # fallback
            
            df_clean['video_name'] = df_clean['frame_file'].apply(extract_video_name)
            
            # Remove warmup videos BEFORE calculating statistics
            print(f'  Before removing warmup: {len(df_clean)} predictions')
            df_clean = df_clean[~df_clean['video_name'].str.contains('warmup', case=False, na=False)]
            print(f'  After removing warmup: {len(df_clean)} predictions')
            
            # Check extracted video names (after warmup removal)
            unique_videos = df_clean['video_name'].nunique()
            unique_participants = df_clean['participant'].nunique()
            print(f'  Extracted {unique_videos} unique videos from {unique_participants} participants')
            
            # Group by participant and video, then take mode of predictions
            print(f'  Grouping by participant and video...')

            #save full csv
            full_csv_path = os.path.join('./results_analysis', f'full_results_{model_name}_{dataset_duration}.csv')
            df_clean.to_csv(full_csv_path, index=False)
            print(f'  Saved full results to {full_csv_path}')
            
            # Function to calculate mode for each participant-video combination
            # MODIFIED: When there's a tie (2 predictions, both different), use the LAST prediction
            def calculate_mode_for_group(group):
                predictions = group['outcome_prediction'].values
                
                # If only 1 prediction, use it
                if len(predictions) == 1:
                    mode_prediction = predictions[0]
                # If 2 predictions and they're different, use the LAST one
                elif len(predictions) == 2 and predictions[0] != predictions[1]:
                    mode_prediction = predictions[-1]  # Use last prediction
                else:
                    # Calculate mode (most frequent prediction)
                    try:
                        mode_series = pd.Series(predictions).mode()
                        if len(mode_series) > 0:
                            mode_prediction = mode_series.iloc[0]
                        else:
                            mode_prediction = predictions[-1]  # fallback to last
                    except:
                        mode_prediction = predictions[-1]  # fallback to last
                
                return pd.Series({
                    'outcome_prediction': mode_prediction,
                    'frame_count': len(group),
                    'frame_files': '; '.join(group['frame_file'].tolist()),
                    'model': group['model'].iloc[0],
                    'dataset_duration': group['dataset_duration'].iloc[0]
                })
            
            # Function to get last frame prediction for each participant-video combination
            def get_last_frame_for_group(group):
                # Sort by frame file to ensure we get the actual last frame
                group_sorted = group.sort_values('frame_file')
                last_row = group_sorted.iloc[-1]
                
                return pd.Series({
                    'outcome_prediction': last_row['outcome_prediction'],
                    'frame_count': len(group),
                    'frame_files': '; '.join(group['frame_file'].tolist()),
                    'model': last_row['model'],
                    'dataset_duration': last_row['dataset_duration']
                })
            
            # Group by BOTH participant AND video_name, then apply mode calculation
            grouped_mode = df_clean.groupby(['participant', 'video_name']).apply(calculate_mode_for_group).reset_index()
            
            # Group by BOTH participant AND video_name, then apply last frame calculation
            grouped_last = df_clean.groupby(['participant', 'video_name']).apply(get_last_frame_for_group).reset_index()
            
            # Save grouped results to CSV
            grouped_mode_csv_path = os.path.join('./results_analysis', f'grouped_mode_results_{model_name}_{dataset_duration}.csv')
            grouped_mode.to_csv(grouped_mode_csv_path, index=False)
            print(f'  Saved grouped MODE results to {grouped_mode_csv_path}')
            
            grouped_last_csv_path = os.path.join('./results_analysis', f'grouped_last_results_{model_name}_{dataset_duration}.csv')
            grouped_last.to_csv(grouped_last_csv_path, index=False)
            print(f'  Saved grouped LAST FRAME results to {grouped_last_csv_path}')
            
            print(f'  Created {len(grouped_mode)} grouped MODE video predictions')
            print(f'  Created {len(grouped_last)} grouped LAST FRAME video predictions')
            
            # Calculate expected combinations
            expected_combinations = unique_participants * unique_videos
            actual_combinations_mode = len(grouped_mode)
            actual_combinations_last = len(grouped_last)
            coverage_mode = actual_combinations_mode / expected_combinations * 100 if expected_combinations > 0 else 0
            coverage_last = actual_combinations_last / expected_combinations * 100 if expected_combinations > 0 else 0
            print(f'  Expected combinations: {unique_participants} participants × {unique_videos} videos = {expected_combinations}')
            print(f'  Actual MODE combinations: {actual_combinations_mode} ({coverage_mode:.1f}% coverage)')
            print(f'  Actual LAST combinations: {actual_combinations_last} ({coverage_last:.1f}% coverage)')
            
            # Add to results
            full_results_mode = pd.concat([full_results_mode, grouped_mode], ignore_index=True)
            full_results_last = pd.concat([full_results_last, grouped_last], ignore_index=True)
            results = pd.concat([results, df_clean], ignore_index=True)
            
            print(f'  Successfully processed {filename}\n')
    
    print(f'Total results: {len(results)} individual frame predictions')
    print(f'Total grouped MODE results: {len(full_results_mode)} video-level predictions')
    print(f'Total grouped LAST FRAME results: {len(full_results_last)} video-level predictions')
    
    return results, full_results_mode, full_results_last

In [20]:
path = '../results/'
results, full_results_mode, full_results_last = load_results(path)

print("\nProcessing and cleaning results...")
print(f"Raw results shape: {results.shape}")
print(f"Grouped MODE results shape: {full_results_mode.shape}")
print(f"Grouped LAST FRAME results shape: {full_results_last.shape}")

# Remove any remaining error entries
if 'outcome_prediction' in results.columns:
    results = results[~results['outcome_prediction'].str.contains("error", case=False, na=False)]
if 'outcome_prediction' in full_results_mode.columns:
    full_results_mode = full_results_mode[~full_results_mode['outcome_prediction'].str.contains("error", case=False, na=False)]
if 'outcome_prediction' in full_results_last.columns:
    full_results_last = full_results_last[~full_results_last['outcome_prediction'].str.contains("error", case=False, na=False)]

print(f"After error removal:")
print(f"Raw results shape: {results.shape}")
print(f"Grouped MODE results shape: {full_results_mode.shape}")
print(f"Grouped LAST FRAME results shape: {full_results_last.shape}")

# Save the results
results.to_csv('all_frame_predictions.csv', index=False)
full_results_mode.to_csv('all_video_predictions_mode.csv', index=False)
full_results_last.to_csv('all_video_predictions_last.csv', index=False)

# Show detailed summary statistics
print(f"\n" + "="*60)
print("SUMMARY STATISTICS")
print("="*60)

print(f"\nUnique models found: {len(full_results_mode['model'].unique())}")
for model in sorted(full_results_mode['model'].unique()):
    print(f"  - {model}")

print(f"\nDetailed breakdown by model and dataset (MODE):")
for model in sorted(full_results_mode['model'].unique()):
    model_data = full_results_mode[full_results_mode['model'] == model]
    n_participants = model_data['participant'].nunique()
    n_videos = model_data['video_name'].nunique()
    dataset_duration = model_data['dataset_duration'].iloc[0] if len(model_data) > 0 else "unknown"
    
    print(f"\n{model}:")
    print(f"  Dataset duration: {dataset_duration}")
    print(f"  Participants: {n_participants}")
    print(f"  Videos: {n_videos}")
    print(f"  Total MODE predictions: {len(model_data)}")
    
    # Also show LAST FRAME stats
    model_data_last = full_results_last[full_results_last['model'] == model]
    print(f"  Total LAST FRAME predictions: {len(model_data_last)}")

# Show dataset duration breakdown
print(f"\nDataset duration breakdown:")
if 'dataset_duration' in full_results_mode.columns:
    duration_counts = full_results_mode['dataset_duration'].value_counts()
    for duration, count in duration_counts.items():
        print(f"  {duration}: {count} MODE predictions")

print(f"\nVideo name examples:")
print(full_results_mode['video_name'].unique()[:10])

Loading results_qwen3_3s.csv
  Model: qwen3_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_qwen3_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_qwen3_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_qwen3_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_qwen3_3s.csv

Loading results_llava32vision_1s.csv
  Model: llava32vision_1s
  Dataset duration: 1s
  Rows: 1902
  Valid predictions: 1902/1902 (100.0%)
  Before removing warmup: 1902 predictions
  After removing warmup: 1730 predictions
  Extracted 30 unique videos from 29 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava32vision_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_qwen3_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_qwen3_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_qwen3_3s.csv

Loading results_llava32vision_1s.csv
  Model: llava32vision_1s
  Dataset duration: 1s
  Rows: 1902
  Valid predictions: 1902/1902 (100.0%)
  Before removing warmup: 1902 predictions
  After removing warmup: 1730 predictions
  Extracted 30 unique videos from 29 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava32vision_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava32vision_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava32vision_1s_1s.csv
  Created 865 grouped MODE video predictions
  Created 865 grouped LAST FRAME video predictions
  Expected combinations: 29 participants × 30 videos = 870
  Actual MODE combinations: 865 (99.4% coverage)
  Actual LAST combinations: 865 (99.4% coverage)
  Successfully processed results_llava32vision_1s.csv

Loading results_mistralsmall32_3s.csv
  Model: mistralsmall32_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_mistralsmall32_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava32vision_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava32vision_1s_1s.csv
  Created 865 grouped MODE video predictions
  Created 865 grouped LAST FRAME video predictions
  Expected combinations: 29 participants × 30 videos = 870
  Actual MODE combinations: 865 (99.4% coverage)
  Actual LAST combinations: 865 (99.4% coverage)
  Successfully processed results_llava32vision_1s.csv

Loading results_mistralsmall32_3s.csv
  Model: mistralsmall32_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_mistralsmall32_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_mistralsmall32_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_mistralsmall32_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_mistralsmall32_3s.csv

Loading results_deepseek-ocr_3s.csv
  Model: deepseek-ocr_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_deepseek-ocr_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_mistralsmall32_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_mistralsmall32_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_mistralsmall32_3s.csv

Loading results_deepseek-ocr_3s.csv
  Model: deepseek-ocr_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_deepseek-ocr_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_deepseek-ocr_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_deepseek-ocr_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_deepseek-ocr_3s.csv

Loading results_gemma3_1s.csv
  Model: gemma3_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_gemma3_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_deepseek-ocr_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_deepseek-ocr_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_deepseek-ocr_3s.csv

Loading results_gemma3_1s.csv
  Model: gemma3_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_gemma3_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_gemma3_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_gemma3_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_gemma3_1s.csv

Loading results_gemma3_3s.csv
  Model: gemma3_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_gemma3_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_gemma3_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_gemma3_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_gemma3_1s.csv

Loading results_gemma3_3s.csv
  Model: gemma3_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_gemma3_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_gemma3_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_gemma3_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_gemma3_3s.csv

Loading results_qwen3_1s.csv
  Model: qwen3_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_qwen3_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_gemma3_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_gemma3_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_gemma3_3s.csv

Loading results_qwen3_1s.csv
  Model: qwen3_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_qwen3_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_qwen3_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_qwen3_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_qwen3_1s.csv

Loading results_llava_1s.csv
  Model: llava_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_qwen3_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_qwen3_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_qwen3_1s.csv

Loading results_llava_1s.csv
  Model: llava_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_llava_1s.csv

Loading results_llava32vision_3s.csv
  Model: llava32vision_3s
  Dataset duration: 3s
  Rows: 3311
  Valid predictions: 3311/3311 (100.0%)
  Before removing warmup: 3311 predictions
  After removing warmup: 3065 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava32vision_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_llava_1s.csv

Loading results_llava32vision_3s.csv
  Model: llava32vision_3s
  Dataset duration: 3s
  Rows: 3311
  Valid predictions: 3311/3311 (100.0%)
  Before removing warmup: 3311 predictions
  After removing warmup: 3065 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava32vision_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava32vision_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava32vision_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_llava32vision_3s.csv

Loading results_llavallama3_3s.csv
  Model: llavallama3_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llavallama3_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava32vision_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava32vision_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_llava32vision_3s.csv

Loading results_llavallama3_3s.csv
  Model: llavallama3_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llavallama3_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llavallama3_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llavallama3_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_llavallama3_3s.csv

Loading results_mistralsmall32_1s.csv
  Model: mistralsmall32_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_mistralsmall32_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llavallama3_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llavallama3_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 511 (56.8% coverage)
  Actual LAST combinations: 511 (56.8% coverage)
  Successfully processed results_llavallama3_3s.csv

Loading results_mistralsmall32_1s.csv
  Model: mistralsmall32_1s
  Dataset duration: 1s
  Rows: 1968
  Valid predictions: 1968/1968 (100.0%)
  Before removing warmup: 1968 predictions
  After removing warmup: 1790 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_mistralsmall32_1s_1s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_mistralsmall32_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_mistralsmall32_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_mistralsmall32_1s.csv

Loading results_llava_3s.csv
  Model: llava_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_mistralsmall32_1s_1s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_mistralsmall32_1s_1s.csv
  Created 895 grouped MODE video predictions
  Created 895 grouped LAST FRAME video predictions
  Expected combinations: 30 participants × 30 videos = 900
  Actual MODE combinations: 895 (99.4% coverage)
  Actual LAST combinations: 895 (99.4% coverage)
  Successfully processed results_mistralsmall32_1s.csv

Loading results_llava_3s.csv
  Model: llava_3s
  Dataset duration: 3s
  Rows: 3312
  Valid predictions: 3312/3312 (100.0%)
  Before removing warmup: 3312 predictions
  After removing warmup: 3066 predictions
  Extracted 30 unique videos from 30 participants
  Grouping by participant and video...
  Saved full results to ./results_analysis/full_results_llava_3s_3s.csv
  Saved grouped MODE results to ./results_analysis/grouped_mode_results_llava_3s_3s.csv
  Saved grouped LAST FRAME results to ./results_analysis/grouped_last_results_llava_3s_3s.csv
  Created 511 grouped MODE video predictions
  Created 511 grouped LAST FRAME video predictions

In [21]:
# Detailed analysis of prediction counts and grouping
print("="*60)
print("DETAILED PREDICTION ANALYSIS - MODE")
print("="*60)

for model in sorted(full_results_mode['model'].unique()):
    print(f"\nModel: {model}")
    model_results = full_results_mode[full_results_mode['model'] == model]
    
    # Count predictions
    poorly_count = model_results['outcome_prediction'].str.contains('poorly', case=False, na=False).sum()
    well_count = model_results['outcome_prediction'].str.contains('well', case=False, na=False).sum()
    total_predictions = len(model_results)
    
    print(f"  Total MODE predictions: {total_predictions}")
    print(f"  Poorly: {poorly_count}")
    print(f"  Well: {well_count}")
    print(f"  Other/Invalid: {total_predictions - poorly_count - well_count}")
    
    # Check for unique participants and videos
    unique_participants = model_results['participant'].nunique()
    unique_videos = model_results['video_name'].nunique()
    unique_combinations = len(model_results[['participant', 'video_name']].drop_duplicates())
    
    print(f"  Unique participants: {unique_participants}")
    print(f"  Unique videos: {unique_videos}")
    print(f"  Unique participant-video combinations: {unique_combinations}")

print("\n" + "="*60)
print("DETAILED PREDICTION ANALYSIS - LAST FRAME")
print("="*60)

for model in sorted(full_results_last['model'].unique()):
    print(f"\nModel: {model}")
    model_results = full_results_last[full_results_last['model'] == model]
    
    # Count predictions
    poorly_count = model_results['outcome_prediction'].str.contains('poorly', case=False, na=False).sum()
    well_count = model_results['outcome_prediction'].str.contains('well', case=False, na=False).sum()
    total_predictions = len(model_results)
    
    print(f"  Total LAST FRAME predictions: {total_predictions}")
    print(f"  Poorly: {poorly_count}")
    print(f"  Well: {well_count}")
    print(f"  Other/Invalid: {total_predictions - poorly_count - well_count}")

# Overall summary
print(f"\n" + "="*60)
print("OVERALL SUMMARY")
print("="*60)
print(f"Total grouped MODE predictions: {len(full_results_mode)}")
print(f"Total grouped LAST FRAME predictions: {len(full_results_last)}")
print(f"\nExpected max predictions per model: participants × videos")
for model in sorted(full_results_mode['model'].unique()):
    model_data_mode = full_results_mode[full_results_mode['model'] == model]
    model_data_last = full_results_last[full_results_last['model'] == model]
    n_participants = model_data_mode['participant'].nunique()
    n_videos = model_data_mode['video_name'].nunique()
    actual_predictions_mode = len(model_data_mode)
    actual_predictions_last = len(model_data_last)
    expected_max = n_participants * n_videos
    print(f"  {model}:")
    print(f"    MODE: {actual_predictions_mode}/{expected_max} predictions ({actual_predictions_mode/expected_max*100:.1f}% coverage)")
    print(f"    LAST: {actual_predictions_last}/{expected_max} predictions ({actual_predictions_last/expected_max*100:.1f}% coverage)")

============================================================
DETAILED PREDICTION ANALYSIS - MODE
============================================================

Model: deepseek-ocr_1s
  Total MODE predictions: 895
  Poorly: 0
  Well: 895
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 895

Model: deepseek-ocr_3s
  Total MODE predictions: 511
  Poorly: 0
  Well: 511
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

Model: gemma3_1s
  Total MODE predictions: 895
  Poorly: 868
  Well: 27
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 895

Model: gemma3_3s
  Total MODE predictions: 511
  Poorly: 502
  Well: 9
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

Model: llava32vision_1s
  Total MODE predictions: 865
  Poorly: 858
  Well: 7
  Other/Invalid: 0
  Unique participants: 29
  Unique videos: 30
  Unique participant-video combinations: 865

Model: llava32vision_3s
  Total MODE predictions: 511
  Poorly: 437
  Well: 74
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

Model: llava_1s
  Total MODE predictions: 895
  Poorly: 892
  Well: 3
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 895

Model: llava_3s
  Total MODE predictions: 511
  Poorly: 511
  Well: 0
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

Model: llavallama3_1s
  Total MODE predictions: 895
  Poorly: 497
  Well: 398
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 895

Model: llavallama3_3s
  Total MODE predictions: 511
  Poorly: 335
  Well: 176
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

Model: mistralsmall32_1s
  Total MODE predictions: 895
  Poorly: 755
  Well: 140
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 895

Model: mistralsmall32_3s
  Total MODE predictions: 511
  Poorly: 455
  Well: 56
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

Model: qwen3_1s
  Total MODE predictions: 895
  Poorly: 471
  Well: 424
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 895

Model: qwen3_3s
  Total MODE predictions: 511
  Poorly: 276
  Well: 235
  Other/Invalid: 0
  Unique participants: 30
  Unique videos: 30
  Unique participant-video combinations: 511

============================================================
DETAILED PREDICTION ANALYSIS - LAST FRAME
============================================================

Model: deepseek-ocr_1s
  Total LAST FRAME predictions: 895
  Poorly: 0
  Well: 895
  Other/Invalid: 0

Model: deepseek-ocr_3s
  Total LAST FRAME predictions: 511
  Poorly: 0
  Well: 511
  Other/Invalid: 0

Model: gemma3_1s
  Total LAST FRAME predictions: 895
  Poorly: 868
  Well: 27
  Other/Invalid: 0

Model: gemma3_3s
  Total LAST FRAME predictions: 511
  Poorly: 496
  Well: 15
  Other/Invalid: 0

Model: llava32vision_1s
  Total LAST FRAME predictions: 865
  Poorly: 858
  Well: 7
  Other/Invalid: 0

Model: llava32vision_3s
  Total LAST FRAME predictions: 511
  Poorly: 427
  Well: 84
  Other/Invalid: 0

Model: llava_1s
  Total LAST FRAME predictions: 895
  Poorly: 892
  Well: 3
  Other/Invalid: 0

Model: llava_3s
  Total LAST FRAME predictions: 511
  Poorly: 505
  Well: 6
  Other/Invalid: 0

Model: llavallama3_1s
  Total LAST FRAME predictions: 895
  Poorly: 497
  Well: 398
  Other/Invalid: 0

Model: llavallama3_3s
  Total LAST FRAME predictions: 511
  Poorly: 283
  Well: 228
  Other/Invalid: 0

Model: mistralsmall32_1s
  Total LAST FRAME predictions: 895
  Poorly: 755
  Well: 140
  Other/Invalid: 0

Model: mistralsmall32_3s
  Total LAST FRAME predictions: 511
  Poorly: 435
  Well: 76
  Other/Invalid: 0

Model: qwen3_1s
  Total LAST FRAME predictions: 895
  Poorly: 471
  Well: 424
  Other/Invalid: 0

Model: qwen3_3s
  Total LAST FRAME predictions: 511
  Poorly: 250
  Well: 261
  Other/Invalid: 0

============================================================
OVERALL SUMMARY
============================================================
Total grouped MODE predictions: 9812
Total grouped LAST FRAME predictions: 9812

Expected max predictions per model: participants × videos
  deepseek-ocr_1s:
    MODE: 895/900 predictions (99.4% coverage)
    LAST: 895/900 predictions (99.4% coverage)
  deepseek-ocr_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)
  gemma3_1s:
    MODE: 895/900 predictions (99.4% coverage)
    LAST: 895/900 predictions (99.4% coverage)
  gemma3_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)
  llava32vision_1s:
    MODE: 865/870 predictions (99.4% coverage)
    LAST: 865/870 predictions (99.4% coverage)
  llava32vision_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)
  llava_1s:
    MODE: 895/900 predictions (99.4% coverage)
    LAST: 895/900 predictions (99.4% coverage)
  llava_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)
  llavallama3_1s:
    MODE: 895/900 predictions (99.4% coverage)
    LAST: 895/900 predictions (99.4% coverage)
  llavallama3_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)
  mistralsmall32_1s:
    MODE: 895/900 predictions (99.4% coverage)
    LAST: 895/900 predictions (99.4% coverage)
  mistralsmall32_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)
  qwen3_1s:
    MODE: 895/900 predictions (99.4% coverage)
    LAST: 895/900 predictions (99.4% coverage)
  qwen3_3s:
    MODE: 511/900 predictions (56.8% coverage)
    LAST: 511/900 predictions (56.8% coverage)

In [22]:
# ===================================================================
# Fix Video Name Mapping Issue and Add Ground Truth Column
# ===================================================================
print("\n" + "="*50)
print("Fixing Video Name Mapping and Adding Ground Truth")
print("="*50)

# Read the ground truth file to get the proper mapping
gt_df_full = pd.read_csv('../../../offshelf_analysis/dataset_scenarios/analyze_predictions.csv')
print(f"Loaded ground truth data: {len(gt_df_full)} videos")

# Create mapping from question format (q_X) to true outcome (1=poorly, 0=well)
question_to_outcome = dict(zip(gt_df_full['Question Mapping'], gt_df_full['True Outcome']))
print("Question to True Outcome mapping (sample):")
for i, (q, outcome) in enumerate(list(question_to_outcome.items())[:5]):
    outcome_label = "poorly" if outcome == 1 else "well"
    print(f"   {q} -> {outcome} ({outcome_label})")

# Add true outcome column to MODE results
print(f"\nAdding ground truth column to MODE results...")
print(f"Before mapping: {len(full_results_mode)} predictions")

full_results_mode['true_outcome'] = full_results_mode['video_name'].map(question_to_outcome)

mapped_count_mode = full_results_mode['true_outcome'].notna().sum()
unmapped_count_mode = full_results_mode['true_outcome'].isna().sum()
print(f"Successfully mapped (MODE): {mapped_count_mode}")
print(f"Unmapped (MODE): {unmapped_count_mode}")

# Add true outcome column to LAST FRAME results
print(f"\nAdding ground truth column to LAST FRAME results...")
print(f"Before mapping: {len(full_results_last)} predictions")

full_results_last['true_outcome'] = full_results_last['video_name'].map(question_to_outcome)

mapped_count_last = full_results_last['true_outcome'].notna().sum()
unmapped_count_last = full_results_last['true_outcome'].isna().sum()
print(f"Successfully mapped (LAST FRAME): {mapped_count_last}")
print(f"Unmapped (LAST FRAME): {unmapped_count_last}")

# Show mapping verification
print(f"\nMapping verification:")
print("Sample video mappings from MODE results:")
sample_mapping = full_results_mode[['video_name', 'true_outcome']].drop_duplicates().head()
for _, row in sample_mapping.iterrows():
    outcome_label = "poorly" if row['true_outcome'] == 1 else ("well" if row['true_outcome'] == 0 else "unknown")
    print(f"   {row['video_name']} -> {row['true_outcome']} ({outcome_label})")

# Save updated results
print(f"\nSaving updated results with ground truth...")
full_results_mode.to_csv('all_video_predictions_mode_with_ground_truth.csv', index=False)
full_results_last.to_csv('all_video_predictions_last_with_ground_truth.csv', index=False)
print(f"Saved MODE to: all_video_predictions_mode_with_ground_truth.csv")
print(f"Saved LAST FRAME to: all_video_predictions_last_with_ground_truth.csv")

==================================================
Fixing Video Name Mapping and Adding Ground Truth
==================================================
Loaded ground truth data: 30 videos
Question to True Outcome mapping (sample):
   q_2 -> 1 (poorly)
   q_3 -> 1 (poorly)
   q_4 -> 1 (poorly)
   q_5 -> 1 (poorly)
   q_6 -> 1 (poorly)

Adding ground truth column to MODE results...
Before mapping: 9812 predictions
Successfully mapped (MODE): 9812
Unmapped (MODE): 0

Adding ground truth column to LAST FRAME results...
Before mapping: 9812 predictions
Successfully mapped (LAST FRAME): 9812
Unmapped (LAST FRAME): 0

Mapping verification:
Sample video mappings from MODE results:
   q_10 -> 0 (well)
   q_12 -> 0 (well)
   q_14 -> 1 (poorly)
   q_15 -> 1 (poorly)
   q_17 -> 1 (poorly)

Saving updated results with ground truth...
Saved MODE to: all_video_predictions_mode_with_ground_truth.csv
Saved LAST FRAME to: all_video_predictions_last_with_ground_truth.csv

In [23]:
# ===================================================================
# Add Human Predictions Column
# ===================================================================
print("\n" + "="*50)
print("Adding Human Predictions Column")
print("="*50)

# Load human predictions data
human_df = pd.read_csv('../../../offshelf_analysis/dataset_scenarios/badidea_ground_truth.csv')
print(f"Loaded human predictions data: {len(human_df)} individual predictions")
print(f"Unique participants: {human_df['participant_id'].nunique()}")
print(f"Unique videos: {human_df['response_video'].nunique()}")

# Filter to only include specific participant IDs
valid_participant_ids = [1048, 1251, 1483, 1676, 2103, 2313, 2698, 2946, 3157, 3203, 3339, 3882, 5009, 5099, 5124, 5233, 5310, 6488, 7136, 7782, 7797, 8184, 8436, 8758, 8786, 9055, 9385, 9777, 9941]
print(f"Filtering to only include {len(valid_participant_ids)} specific participants")
print(f"Original dataset size: {len(human_df)}")
human_df = human_df[human_df['participant_id'].isin(valid_participant_ids)]
print(f"Filtered dataset size: {len(human_df)}")
print(f"Participants after filtering: {human_df['participant_id'].nunique()}")

# Create mapping from (participant_id, video_name) to human prediction
human_prediction_map = {}
for _, row in human_df.iterrows():
    participant_id = str(row['participant_id'])  # Convert to string to match
    video_name = row['response_video']  # Already in q_X format
    human_prediction = row['class']  # 1=poorly, 0=well
    
    human_prediction_map[(participant_id, video_name)] = human_prediction

print(f"Created human prediction mapping with {len(human_prediction_map)} entries")
print("Sample human predictions:", dict(list(human_prediction_map.items())[:3]))

# Add human prediction column to MODE results
def get_human_prediction(row):
    participant_id = str(row['participant'])
    video_name = row['video_name']
    return human_prediction_map.get((participant_id, video_name), np.nan)

print(f"\nAdding human prediction column to MODE results...")
full_results_mode['human_prediction'] = full_results_mode.apply(get_human_prediction, axis=1)

# Check how many predictions got human matches
human_mapped_count_mode = full_results_mode['human_prediction'].notna().sum()
human_unmapped_count_mode = full_results_mode['human_prediction'].isna().sum()
print(f"Successfully mapped to human predictions (MODE): {human_mapped_count_mode}")
print(f"Unmapped (MODE): {human_unmapped_count_mode}")

# Add human prediction column to LAST FRAME results
print(f"\nAdding human prediction column to LAST FRAME results...")
full_results_last['human_prediction'] = full_results_last.apply(get_human_prediction, axis=1)

# Check how many predictions got human matches
human_mapped_count_last = full_results_last['human_prediction'].notna().sum()
human_unmapped_count_last = full_results_last['human_prediction'].isna().sum()
print(f"Successfully mapped to human predictions (LAST FRAME): {human_mapped_count_last}")
print(f"Unmapped (LAST FRAME): {human_unmapped_count_last}")

# Show mapping verification
print(f"\nHuman prediction mapping verification (MODE):")
print("Sample participant-video-human prediction mappings:")
sample_mapping = full_results_mode[['participant', 'video_name', 'human_prediction', 'true_outcome']].dropna().head()
for _, row in sample_mapping.iterrows():
    human_label = "poorly" if row['human_prediction'] == 1 else ("well" if row['human_prediction'] == 0 else "unknown")
    true_label = "poorly" if row['true_outcome'] == 1 else ("well" if row['true_outcome'] == 0 else "unknown")
    print(f"   Participant {row['participant']}, Video {row['video_name']}: Human={row['human_prediction']} ({human_label}), True={row['true_outcome']} ({true_label})")

# Save updated results with both ground truth and human predictions
print(f"\nSaving updated results with ground truth and human predictions...")
full_results_mode.to_csv('all_video_predictions_mode_with_ground_truth_and_human.csv', index=False)
full_results_last.to_csv('all_video_predictions_last_with_ground_truth_and_human.csv', index=False)
print(f"Saved MODE to: all_video_predictions_mode_with_ground_truth_and_human.csv")
print(f"Saved LAST FRAME to: all_video_predictions_last_with_ground_truth_and_human.csv")

print(f"\nMODE DataFrame columns: {full_results_mode.columns.tolist()}")
print(f"Total MODE predictions: {len(full_results_mode)}")
print(f"MODE Predictions with both ground truth and human data: {len(full_results_mode.dropna(subset=['true_outcome', 'human_prediction']))}")

print(f"\nLAST FRAME DataFrame columns: {full_results_last.columns.tolist()}")
print(f"Total LAST FRAME predictions: {len(full_results_last)}")
print(f"LAST FRAME Predictions with both ground truth and human data: {len(full_results_last.dropna(subset=['true_outcome', 'human_prediction']))}")

==================================================
Adding Human Predictions Column
==================================================
Loaded human predictions data: 865 individual predictions
Unique participants: 29
Unique videos: 30
Filtering to only include 29 specific participants
Original dataset size: 865
Filtered dataset size: 865
Participants after filtering: 29

Created human prediction mapping with 865 entries
Sample human predictions: {('1048', 'q_10'): 0, ('1048', 'q_11'): 0, ('1048', 'q_12'): 1}

Adding human prediction column to MODE results...
Successfully mapped to human predictions (MODE): 9476
Unmapped (MODE): 336

Adding human prediction column to LAST FRAME results...
Successfully mapped to human predictions (LAST FRAME): 9476
Unmapped (LAST FRAME): 336

Human prediction mapping verification (MODE):
Sample participant-video-human prediction mappings:
   Participant 1048, Video q_10: Human=0.0 (well), True=0 (well)
   Participant 1048, Video q_12: Human=1.0 (poorly), True=0 (well)
   Participant 1048, Video q_14: Human=0.0 (well), True=1 (poorly)
   Participant 1048, Video q_15: Human=1.0 (poorly), True=1 (poorly)
   Participant 1048, Video q_17: Human=1.0 (poorly), True=1 (poorly)

Saving updated results with ground truth and human predictions...
Saved MODE to: all_video_predictions_mode_with_ground_truth_and_human.csv
Saved LAST FRAME to: all_video_predictions_last_with_ground_truth_and_human.csv

MODE DataFrame columns: ['participant', 'video_name', 'outcome_prediction', 'frame_count', 'frame_files', 'model', 'dataset_duration', 'true_outcome', 'human_prediction']
Total MODE predictions: 9812
MODE Predictions with both ground truth and human data: 9476

LAST FRAME DataFrame columns: ['participant', 'video_name', 'outcome_prediction', 'frame_count', 'frame_files', 'model', 'dataset_duration', 'true_outcome', 'human_prediction']
Total LAST FRAME predictions: 9812
LAST FRAME Predictions with both ground truth and human data: 9476

In [24]:
# ===================================================================
# Calculate Model vs Human Agreement Metrics - MODE (Per Participant)
# ===================================================================
print("\n" + "="*60)
print("CALCULATING MODE vs HUMAN AGREEMENT METRICS (PER PARTICIPANT)")
print("="*60)

# First, convert text predictions to numeric for all models (MODE)
print("Converting MODE predictions to numeric format...")
full_results_mode['outcome_prediction_numeric'] = full_results_mode['outcome_prediction'].apply(
    lambda x: 1 if 'poorly' in str(x).lower() else (0 if 'well' in str(x).lower() else np.nan)
)

# Remove any NaN predictions - need both model prediction and human prediction
full_results_mode_clean = full_results_mode.dropna(subset=['outcome_prediction_numeric', 'human_prediction'])
print(f"Clean MODE predictions with both model and human data: {len(full_results_mode_clean)}")

# Models and metrics dataframe for MODE - Now with per-participant stats
model_human_agreement_mode_df = pd.DataFrame(columns=[
    'model', 'accuracy_mean', 'accuracy_std', 'precision_mean', 'precision_std',
    'recall_mean', 'recall_std', 'f1_score_mean', 'f1_score_std',
    'poorly_ratio', 'n_participants', 'n_videos'
])

print("\nEvaluating MODE vs human agreement per participant...")

# Evaluate each model
for model in sorted(full_results_mode_clean['model'].unique()):
    print(f"\nProcessing model: {model}")
    model_results = full_results_mode_clean[full_results_mode_clean['model'] == model]
    
    print(f"  Total participant-video combinations: {len(model_results)}")
    print(f"  Unique videos: {model_results['video_name'].nunique()}")
    print(f"  Unique participants: {model_results['participant'].nunique()}")
    
    # Calculate overall poorly ratio (not per participant)
    n_poorly = (model_results['outcome_prediction_numeric'] == 1).sum()
    n_total = len(model_results)
    poorly_ratio = n_poorly / n_total if n_total > 0 else 0
    print(f"  Overall poorly predictions: {n_poorly}/{n_total} ({poorly_ratio:.3f})")
    
    # Calculate metrics PER PARTICIPANT
    participant_metrics = []
    
    for participant in sorted(model_results['participant'].unique()):
        participant_data = model_results[model_results['participant'] == participant]
        
        y_pred = participant_data['outcome_prediction_numeric'].values  # Model predictions
        y_human = participant_data['human_prediction'].values           # Human predictions
        
        # Calculate metrics for this participant
        accuracy = accuracy_score(y_human, y_pred)
        precision = precision_score(y_human, y_pred, zero_division=0)
        recall = recall_score(y_human, y_pred, zero_division=0)
        f1 = f1_score(y_human, y_pred, zero_division=0)
        
        participant_metrics.append({
            'participant': participant,
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'n_predictions': len(participant_data)
        })
    
    # Convert to dataframe for easy calculation
    participant_metrics_df = pd.DataFrame(participant_metrics)
    
    # Calculate mean and std across participants
    accuracy_mean = participant_metrics_df['accuracy'].mean()
    accuracy_std = participant_metrics_df['accuracy'].std()
    precision_mean = participant_metrics_df['precision'].mean()
    precision_std = participant_metrics_df['precision'].std()
    recall_mean = participant_metrics_df['recall'].mean()
    recall_std = participant_metrics_df['recall'].std()
    f1_mean = participant_metrics_df['f1_score'].mean()
    f1_std = participant_metrics_df['f1_score'].std()
    
    print(f"  Agreement with humans (averaged across {len(participant_metrics)} participants):")
    print(f"    Accuracy: {accuracy_mean:.3f} ± {accuracy_std:.3f}")
    print(f"    Precision: {precision_mean:.3f} ± {precision_std:.3f}")
    print(f"    Recall: {recall_mean:.3f} ± {recall_std:.3f}")
    print(f"    F1 Score: {f1_mean:.3f} ± {f1_std:.3f}")
    
    # Add to results dataframe
    df_pred = pd.DataFrame({
        'model': [model],
        'accuracy_mean': [accuracy_mean],
        'accuracy_std': [accuracy_std],
        'precision_mean': [precision_mean],
        'precision_std': [precision_std],
        'recall_mean': [recall_mean],
        'recall_std': [recall_std],
        'f1_score_mean': [f1_mean],
        'f1_score_std': [f1_std],
        'poorly_ratio': [poorly_ratio],
        'n_participants': [len(participant_metrics)],
        'n_videos': [model_results['video_name'].nunique()]
    })
    model_human_agreement_mode_df = pd.concat([model_human_agreement_mode_df, df_pred], ignore_index=True)

# Save the MODE performance results
print(f"\n" + "="*60)
print("SAVING MODE RESULTS")
print("="*60)
model_human_agreement_mode_df.to_csv('model_human_agreement_mode_metrics.csv', index=False)
full_results_mode_clean.to_csv('all_predictions_mode_clean.csv', index=False)

print("Saved MODE files:")
print("  - model_human_agreement_mode_metrics.csv")
print("  - all_predictions_mode_clean.csv")

# Display MODE results
print(f"\n" + "="*60)
print("MODE vs HUMAN AGREEMENT SUMMARY (PER PARTICIPANT)")
print("="*60)
model_human_agreement_mode_df = model_human_agreement_mode_df.sort_values('accuracy_mean', ascending=False)
print(model_human_agreement_mode_df.to_string(index=False, float_format='%.3f'))

model_human_agreement_mode_df

============================================================
CALCULATING MODE vs HUMAN AGREEMENT METRICS (PER PARTICIPANT)
============================================================
Converting MODE predictions to numeric format...
Clean MODE predictions with both model and human data: 9476

Evaluating MODE vs human agreement per participant...

Processing model: deepseek-ocr_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 0/865 (0.000)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.535 ± 0.098
    Precision: 0.000 ± 0.000
    Recall: 0.000 ± 0.000
    F1 Score: 0.000 ± 0.000

Processing model: deepseek-ocr_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 0/493 (0.000)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.518 ± 0.143
    Precision: 0.000 ± 0.000
    Recall: 0.000 ± 0.000
    F1 Score: 0.000 ± 0.000

Processing model: gemma3_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 838/865 (0.969)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.450 ± 0.104
    Precision: 0.454 ± 0.106
    Recall: 0.945 ± 0.100
    F1 Score: 0.608 ± 0.112

Processing model: gemma3_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 484/493 (0.982)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.467 ± 0.159
    Precision: 0.472 ± 0.154
    Recall: 0.957 ± 0.111
    F1 Score: 0.619 ± 0.159

Processing model: llava32vision_1s
  Total participant-video combinations: 835
  Unique videos: 30
  Unique participants: 28
  Overall poorly predictions: 828/835 (0.992)
  Agreement with humans (averaged across 28 participants):
    Accuracy: 0.460 ± 0.100
    Precision: 0.463 ± 0.100
    Recall: 0.985 ± 0.036
    F1 Score: 0.623 ± 0.098

Processing model: llava32vision_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 419/493 (0.850)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.470 ± 0.142
    Precision: 0.472 ± 0.203
    Recall: 0.852 ± 0.300
    F1 Score: 0.564 ± 0.196

Processing model: llava_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 863/865 (0.998)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.463 ± 0.097
    Precision: 0.464 ± 0.097
    Recall: 0.996 ± 0.016
    F1 Score: 0.627 ± 0.096

Processing model: llava_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 493/493 (1.000)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.482 ± 0.143
    Precision: 0.482 ± 0.143
    Recall: 1.000 ± 0.000
    F1 Score: 0.637 ± 0.141

Processing model: llavallama3_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 475/865 (0.549)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.462 ± 0.101
    Precision: 0.411 ± 0.176
    Recall: 0.510 ± 0.285
    F1 Score: 0.425 ± 0.188

Processing model: llavallama3_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 320/493 (0.649)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.432 ± 0.163
    Precision: 0.374 ± 0.232
    Recall: 0.553 ± 0.359
    F1 Score: 0.427 ± 0.258

Processing model: mistralsmall32_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 725/865 (0.838)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.458 ± 0.118
    Precision: 0.450 ± 0.111
    Recall: 0.812 ± 0.220
    F1 Score: 0.565 ± 0.136

Processing model: mistralsmall32_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 437/493 (0.886)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.437 ± 0.186
    Precision: 0.444 ± 0.174
    Recall: 0.820 ± 0.247
    F1 Score: 0.562 ± 0.198

Processing model: qwen3_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 442/865 (0.511)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.487 ± 0.086
    Precision: 0.458 ± 0.211
    Recall: 0.482 ± 0.303
    F1 Score: 0.419 ± 0.194

Processing model: qwen3_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 258/493 (0.523)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.478 ± 0.149
    Precision: 0.414 ± 0.300
    Recall: 0.468 ± 0.385
    F1 Score: 0.388 ± 0.274

============================================================
SAVING MODE RESULTS
============================================================
Saved MODE files:
  - model_human_agreement_mode_metrics.csv
  - all_predictions_mode_clean.csv

============================================================
MODE vs HUMAN AGREEMENT SUMMARY (PER PARTICIPANT)
============================================================
            model  accuracy_mean  accuracy_std  precision_mean  precision_std  recall_mean  recall_std  f1_score_mean  f1_score_std  poorly_ratio n_participants n_videos
  deepseek-ocr_1s          0.535         0.098           0.000          0.000        0.000       0.000          0.000         0.000         0.000             29       30
  deepseek-ocr_3s          0.518         0.143           0.000          0.000        0.000       0.000          0.000         0.000         0.000             29       30
         qwen3_1s          0.487         0.086           0.458          0.211        0.482       0.303          0.419         0.194         0.511             29       30
         llava_3s          0.482         0.143           0.482          0.143        1.000       0.000          0.637         0.141         1.000             29       30
         qwen3_3s          0.478         0.149           0.414          0.300        0.468       0.385          0.388         0.274         0.523             29       30
 llava32vision_3s          0.470         0.142           0.472          0.203        0.852       0.300          0.564         0.196         0.850             29       30
        gemma3_3s          0.467         0.159           0.472          0.154        0.957       0.111          0.619         0.159         0.982             29       30
         llava_1s          0.463         0.097           0.464          0.097        0.996       0.016          0.627         0.096         0.998             29       30
   llavallama3_1s          0.462         0.101           0.411          0.176        0.510       0.285          0.425         0.188         0.549             29       30
 llava32vision_1s          0.460         0.100           0.463          0.100        0.985       0.036          0.623         0.098         0.992             28       30
mistralsmall32_1s          0.458         0.118           0.450          0.111        0.812       0.220          0.565         0.136         0.838             29       30
        gemma3_1s          0.450         0.104           0.454          0.106        0.945       0.100          0.608         0.112         0.969             29       30
mistralsmall32_3s          0.437         0.186           0.444          0.174        0.820       0.247          0.562         0.198         0.886             29       30
   llavallama3_3s          0.432         0.163           0.374          0.232        0.553       0.359          0.427         0.258         0.649             29       30

,model,accuracy_mean,accuracy_std,precision_mean,precision_std,recall_mean,recall_std,f1_score_mean,f1_score_std,poorly_ratio,n_participants,n_videos
0,deepseek-ocr_1s,0.535076,0.098268,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29,30
1,deepseek-ocr_3s,0.518167,0.143335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29,30
12,qwen3_1s,0.487174,0.086461,0.458194,0.210780,0.482107,0.303229,0.419014,0.194160,0.510983,29,30
7,llava_3s,0.481833,0.143335,0.481833,0.143335,1.000000,0.000000,0.637276,0.141090,1.000000,29,30
13,qwen3_3s,0.477507,0.149222,0.414088,0.300088,0.467708,0.385472,0.388286,0.274230,0.523327,29,30
5,llava32vision_3s,0.469821,0.141759,0.472038,0.203038,0.851900,0.299618,0.564349,0.196473,0.849899,29,30
3,gemma3_3s,0.466823,0.159358,0.471704,0.153923,0.957184,0.110638,0.619374,0.158773,0.981744,29,30
6,llava_1s,0.462625,0.096568,0.463854,0.097450,0.995785,0.015829,0.626532,0.095623,0.997688,29,30
8,llavallama3_1s,0.462379,0.100935,0.411010,0.175778,0.510358,0.284523,0.425458,0.187701,0.549133,29,30
4,llava32vision_1s,0.460053,0.099607,0.462795,0.099613,0.985038,0.036074,0.623140,0.098335,0.991617,28,30
10,mistralsmall32_1s,0.458274,0.117591,0.450334,0.110923,0.812133,0.220127,0.565485,0.135730,0.838150,29,30
2,gemma3_1s,0.449982,0.103732,0.454464,0.106167,0.945249,0.100007,0.607730,0.111512,0.968786,29,30
11,mistralsmall32_3s,0.436607,0.185634,0.444228,0.174050,0.819542,0.247371,0.561559,0.197515,0.886410,29,30
9,llavallama3_3s,0.431625,0.162919,0.373884,0.231813,0.552784,0.359167,0.426526,0.257813,0.649087,29,30

In [25]:
# ===================================================================
# Calculate Model vs Human Agreement Metrics - LAST (Per Participant)
# ===================================================================
print("\n" + "="*60)
print("CALCULATING LAST vs HUMAN AGREEMENT METRICS (PER PARTICIPANT)")
print("="*60)

# First, convert text predictions to numeric for all models (LAST)
print("Converting LAST predictions to numeric format...")
full_results_last['outcome_prediction_numeric'] = full_results_last['outcome_prediction'].apply(
    lambda x: 1 if 'poorly' in str(x).lower() else (0 if 'well' in str(x).lower() else np.nan)
)

# Remove any NaN predictions - need both model prediction and human prediction
full_results_last_clean = full_results_last.dropna(subset=['outcome_prediction_numeric', 'human_prediction'])
print(f"Clean LAST predictions with both model and human data: {len(full_results_last_clean)}")

# Models and metrics dataframe for LAST - Now with per-participant stats
model_human_agreement_last_df = pd.DataFrame(columns=[
    'model', 'accuracy_mean', 'accuracy_std', 'precision_mean', 'precision_std',
    'recall_mean', 'recall_std', 'f1_score_mean', 'f1_score_std',
    'poorly_ratio', 'n_participants', 'n_videos'
])

print("\nEvaluating LAST vs human agreement per participant...")

# Evaluate each model
for model in sorted(full_results_last_clean['model'].unique()):
    print(f"\nProcessing model: {model}")
    model_results = full_results_last_clean[full_results_last_clean['model'] == model]
    
    print(f"  Total participant-video combinations: {len(model_results)}")
    print(f"  Unique videos: {model_results['video_name'].nunique()}")
    print(f"  Unique participants: {model_results['participant'].nunique()}")
    
    # Calculate overall poorly ratio (not per participant)
    n_poorly = (model_results['outcome_prediction_numeric'] == 1).sum()
    n_total = len(model_results)
    poorly_ratio = n_poorly / n_total if n_total > 0 else 0
    print(f"  Overall poorly predictions: {n_poorly}/{n_total} ({poorly_ratio:.3f})")
    
    # Calculate metrics PER PARTICIPANT
    participant_metrics = []
    
    for participant in sorted(model_results['participant'].unique()):
        participant_data = model_results[model_results['participant'] == participant]
        
        y_pred = participant_data['outcome_prediction_numeric'].values  # Model predictions
        y_human = participant_data['human_prediction'].values           # Human predictions
        
        # Calculate metrics for this participant
        accuracy = accuracy_score(y_human, y_pred)
        precision = precision_score(y_human, y_pred, zero_division=0)
        recall = recall_score(y_human, y_pred, zero_division=0)
        f1 = f1_score(y_human, y_pred, zero_division=0)
        
        participant_metrics.append({
            'participant': participant,
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'n_predictions': len(participant_data)
        })
    
    # Convert to dataframe for easy calculation
    participant_metrics_df = pd.DataFrame(participant_metrics)
    
    # Calculate mean and std across participants
    accuracy_mean = participant_metrics_df['accuracy'].mean()
    accuracy_std = participant_metrics_df['accuracy'].std()
    precision_mean = participant_metrics_df['precision'].mean()
    precision_std = participant_metrics_df['precision'].std()
    recall_mean = participant_metrics_df['recall'].mean()
    recall_std = participant_metrics_df['recall'].std()
    f1_mean = participant_metrics_df['f1_score'].mean()
    f1_std = participant_metrics_df['f1_score'].std()
    
    print(f"  Agreement with humans (averaged across {len(participant_metrics)} participants):")
    print(f"    Accuracy: {accuracy_mean:.3f} ± {accuracy_std:.3f}")
    print(f"    Precision: {precision_mean:.3f} ± {precision_std:.3f}")
    print(f"    Recall: {recall_mean:.3f} ± {recall_std:.3f}")
    print(f"    F1 Score: {f1_mean:.3f} ± {f1_std:.3f}")
    
    # Add to results dataframe
    df_pred = pd.DataFrame({
        'model': [model],
        'accuracy_mean': [accuracy_mean],
        'accuracy_std': [accuracy_std],
        'precision_mean': [precision_mean],
        'precision_std': [precision_std],
        'recall_mean': [recall_mean],
        'recall_std': [recall_std],
        'f1_score_mean': [f1_mean],
        'f1_score_std': [f1_std],
        'poorly_ratio': [poorly_ratio],
        'n_participants': [len(participant_metrics)],
        'n_videos': [model_results['video_name'].nunique()]
    })
    model_human_agreement_last_df = pd.concat([model_human_agreement_last_df, df_pred], ignore_index=True)

# Save the LAST performance results
print(f"\n" + "="*60)
print("SAVING LAST RESULTS")
print("="*60)
model_human_agreement_last_df.to_csv('model_human_agreement_last_metrics.csv', index=False)
full_results_last_clean.to_csv('all_predictions_last_clean.csv', index=False)

print("Saved LAST files:")
print("  - model_human_agreement_last_metrics.csv")
print("  - all_predictions_last_clean.csv")

# Display LAST results
print(f"\n" + "="*60)
print("LAST vs HUMAN AGREEMENT SUMMARY (PER PARTICIPANT)")
print("="*60)
model_human_agreement_last_df = model_human_agreement_last_df.sort_values('accuracy_mean', ascending=False)
print(model_human_agreement_last_df.to_string(index=False, float_format='%.3f'))

model_human_agreement_last_df

============================================================
CALCULATING LAST vs HUMAN AGREEMENT METRICS (PER PARTICIPANT)
============================================================
Converting LAST predictions to numeric format...
Clean LAST predictions with both model and human data: 9476

Evaluating LAST vs human agreement per participant...

Processing model: deepseek-ocr_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 0/865 (0.000)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.535 ± 0.098
    Precision: 0.000 ± 0.000
    Recall: 0.000 ± 0.000
    F1 Score: 0.000 ± 0.000

Processing model: deepseek-ocr_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 0/493 (0.000)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.518 ± 0.143
    Precision: 0.000 ± 0.000
    Recall: 0.000 ± 0.000
    F1 Score: 0.000 ± 0.000

Processing model: gemma3_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 838/865 (0.969)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.450 ± 0.104
    Precision: 0.454 ± 0.106
    Recall: 0.945 ± 0.100
    F1 Score: 0.608 ± 0.112

Processing model: gemma3_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 478/493 (0.970)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.459 ± 0.154
    Precision: 0.467 ± 0.154
    Recall: 0.937 ± 0.137
    F1 Score: 0.610 ± 0.160

Processing model: llava32vision_1s
  Total participant-video combinations: 835
  Unique videos: 30
  Unique participants: 28
  Overall poorly predictions: 828/835 (0.992)
  Agreement with humans (averaged across 28 participants):
    Accuracy: 0.460 ± 0.100
    Precision: 0.463 ± 0.100
    Recall: 0.985 ± 0.036
    F1 Score: 0.623 ± 0.098

Processing model: llava32vision_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 409/493 (0.830)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.455 ± 0.129
    Precision: 0.445 ± 0.169
    Recall: 0.817 ± 0.330
    F1 Score: 0.538 ± 0.208

Processing model: llava_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 863/865 (0.998)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.463 ± 0.097
    Precision: 0.464 ± 0.097
    Recall: 0.996 ± 0.016
    F1 Score: 0.627 ± 0.096

Processing model: llava_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 487/493 (0.988)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.482 ± 0.142
    Precision: 0.482 ± 0.144
    Recall: 0.987 ± 0.043
    F1 Score: 0.634 ± 0.142

Processing model: llavallama3_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 475/865 (0.549)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.462 ± 0.101
    Precision: 0.411 ± 0.176
    Recall: 0.510 ± 0.285
    F1 Score: 0.425 ± 0.188

Processing model: llavallama3_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 273/493 (0.554)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.480 ± 0.146
    Precision: 0.479 ± 0.252
    Recall: 0.516 ± 0.288
    F1 Score: 0.446 ± 0.210

Processing model: mistralsmall32_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 725/865 (0.838)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.458 ± 0.118
    Precision: 0.450 ± 0.111
    Recall: 0.812 ± 0.220
    F1 Score: 0.565 ± 0.136

Processing model: mistralsmall32_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 417/493 (0.846)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.456 ± 0.179
    Precision: 0.456 ± 0.173
    Recall: 0.803 ± 0.264
    F1 Score: 0.562 ± 0.198

Processing model: qwen3_1s
  Total participant-video combinations: 865
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 442/865 (0.511)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.487 ± 0.086
    Precision: 0.458 ± 0.211
    Recall: 0.482 ± 0.303
    F1 Score: 0.419 ± 0.194

Processing model: qwen3_3s
  Total participant-video combinations: 493
  Unique videos: 30
  Unique participants: 29
  Overall poorly predictions: 233/493 (0.473)
  Agreement with humans (averaged across 29 participants):
    Accuracy: 0.485 ± 0.133
    Precision: 0.446 ± 0.318
    Recall: 0.424 ± 0.340
    F1 Score: 0.387 ± 0.263

============================================================
SAVING LAST RESULTS
============================================================
Saved LAST files:
  - model_human_agreement_last_metrics.csv
  - all_predictions_last_clean.csv

============================================================
LAST vs HUMAN AGREEMENT SUMMARY (PER PARTICIPANT)
============================================================
            model  accuracy_mean  accuracy_std  precision_mean  precision_std  recall_mean  recall_std  f1_score_mean  f1_score_std  poorly_ratio n_participants n_videos
  deepseek-ocr_1s          0.535         0.098           0.000          0.000        0.000       0.000          0.000         0.000         0.000             29       30
  deepseek-ocr_3s          0.518         0.143           0.000          0.000        0.000       0.000          0.000         0.000         0.000             29       30
         qwen3_1s          0.487         0.086           0.458          0.211        0.482       0.303          0.419         0.194         0.511             29       30
         qwen3_3s          0.485         0.133           0.446          0.318        0.424       0.340          0.387         0.263         0.473             29       30
         llava_3s          0.482         0.142           0.482          0.144        0.987       0.043          0.634         0.142         0.988             29       30
   llavallama3_3s          0.480         0.146           0.479          0.252        0.516       0.288          0.446         0.210         0.554             29       30
         llava_1s          0.463         0.097           0.464          0.097        0.996       0.016          0.627         0.096         0.998             29       30
   llavallama3_1s          0.462         0.101           0.411          0.176        0.510       0.285          0.425         0.188         0.549             29       30
 llava32vision_1s          0.460         0.100           0.463          0.100        0.985       0.036          0.623         0.098         0.992             28       30
        gemma3_3s          0.459         0.154           0.467          0.154        0.937       0.137          0.610         0.160         0.970             29       30
mistralsmall32_1s          0.458         0.118           0.450          0.111        0.812       0.220          0.565         0.136         0.838             29       30
mistralsmall32_3s          0.456         0.179           0.456          0.173        0.803       0.264          0.562         0.198         0.846             29       30
 llava32vision_3s          0.455         0.129           0.445          0.169        0.817       0.330          0.538         0.208         0.830             29       30
        gemma3_1s          0.450         0.104           0.454          0.106        0.945       0.100          0.608         0.112         0.969             29       30

,model,accuracy_mean,accuracy_std,precision_mean,precision_std,recall_mean,recall_std,f1_score_mean,f1_score_std,poorly_ratio,n_participants,n_videos
0,deepseek-ocr_1s,0.535076,0.098268,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29,30
1,deepseek-ocr_3s,0.518167,0.143335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29,30
12,qwen3_1s,0.487174,0.086461,0.458194,0.210780,0.482107,0.303229,0.419014,0.194160,0.510983,29,30
13,qwen3_3s,0.485018,0.133105,0.446287,0.318275,0.423585,0.339584,0.387234,0.262738,0.472617,29,30
7,llava_3s,0.481946,0.141508,0.481571,0.144328,0.987003,0.042686,0.634223,0.142410,0.987830,29,30
9,llavallama3_3s,0.479983,0.146163,0.479465,0.252438,0.515886,0.287704,0.445664,0.209609,0.553753,29,30
6,llava_1s,0.462625,0.096568,0.463854,0.097450,0.995785,0.015829,0.626532,0.095623,0.997688,29,30
8,llavallama3_1s,0.462379,0.100935,0.411010,0.175778,0.510358,0.284523,0.425458,0.187701,0.549133,29,30
4,llava32vision_1s,0.460053,0.099607,0.462795,0.099613,0.985038,0.036074,0.623140,0.098335,0.991617,28,30
3,gemma3_3s,0.458966,0.154076,0.466509,0.154305,0.937482,0.137326,0.610137,0.160058,0.969574,29,30
10,mistralsmall32_1s,0.458274,0.117591,0.450334,0.110923,0.812133,0.220127,0.565485,0.135730,0.838150,29,30
11,mistralsmall32_3s,0.456100,0.178976,0.455858,0.172877,0.802780,0.264328,0.562074,0.197954,0.845842,29,30
5,llava32vision_3s,0.455164,0.128901,0.445246,0.168862,0.816812,0.330385,0.538005,0.207916,0.829615,29,30
2,gemma3_1s,0.449982,0.103732,0.454464,0.106167,0.945249,0.100007,0.607730,0.111512,0.968786,29,30

In [ ]:
# ===================================================================
# SUMMARY: MODE vs LAST FRAME Comparison (Per Participant Averages)
# ===================================================================
print("\n" + "="*80)
print("SUMMARY: Comparison of MODE vs LAST FRAME Predictions (Per Participant)")
print("="*80)

print("\n" + "="*80)
print("Agreement with Individual Humans (Mean ± Std across participants)")
print("="*80)

print("\nMODE Predictions:")
display_cols = ['model', 'accuracy_mean', 'accuracy_std', 'precision_mean', 'precision_std', 
                'recall_mean', 'recall_std', 'f1_score_mean', 'f1_score_std', 'poorly_ratio']
print(model_human_agreement_mode_df[display_cols].round(3))

print("\nLAST FRAME Predictions:")
print(model_human_agreement_last_df[display_cols].round(3))

In [ ]:
# ===================================================================
# Visualization: MODE vs LAST FRAME Performance Comparison (with std error bars)
# ===================================================================
fig, axes = plt.subplots(2, 2, figsize=(18, 14))
fig.suptitle('Reaction Analysis - VLM Performance: MODE vs LAST FRAME Predictions\n(Mean ± Std across participants)', 
             fontsize=16, fontweight='bold')

metrics_to_plot = ['accuracy', 'precision', 'recall', 'f1_score']
metric_titles = ['Accuracy', 'Precision', 'Recall', 'F1 Score']

for idx, (metric, title) in enumerate(zip(metrics_to_plot, metric_titles)):
    ax = axes[idx // 2, idx % 2]
    
    # Get data for plotting
    models = sorted(model_human_agreement_mode_df['model'].unique())
    mode_values = [model_human_agreement_mode_df[model_human_agreement_mode_df['model'] == m][f'{metric}_mean'].values[0] for m in models]
    mode_stds = [model_human_agreement_mode_df[model_human_agreement_mode_df['model'] == m][f'{metric}_std'].values[0] for m in models]
    last_values = [model_human_agreement_last_df[model_human_agreement_last_df['model'] == m][f'{metric}_mean'].values[0] for m in models]
    last_stds = [model_human_agreement_last_df[model_human_agreement_last_df['model'] == m][f'{metric}_std'].values[0] for m in models]
    
    x = np.arange(len(models))
    width = 0.35
    
    # Plot bars with error bars
    bars1 = ax.bar(x - width/2, mode_values, width, yerr=mode_stds, 
                   label='Mode', alpha=0.8, color='steelblue', capsize=3)
    bars2 = ax.bar(x + width/2, last_values, width, yerr=last_stds,
                   label='Last Frame', alpha=0.8, color='coral', capsize=3)
    
    ax.set_xlabel('Model', fontsize=11)
    ax.set_ylabel(title, fontsize=11)
    ax.set_title(f'{title} - Agreement with Humans (Mean ± Std)', fontsize=12, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(models, rotation=45, ha='right', fontsize=8)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3, axis='y')
    ax.set_ylim(0, 1)
    
    # Add value labels on bars
    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{height:.2f}',
                   ha='center', va='bottom', fontsize=6)

plt.tight_layout()
plt.savefig('mode_vs_last_frame_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nVisualization saved to 'mode_vs_last_frame_comparison.png'")

In [ ]:
# ===================================================================
# Detailed Comparison Table: MODE vs LAST FRAME (Per Participant Means)
# ===================================================================
print("\n" + "="*80)
print("Detailed Comparison: MODE vs LAST FRAME (Agreement with Humans, Per Participant)")
print("="*80)

# Create comparison dataframe
comparison_data = []
for model in sorted(model_human_agreement_mode_df['model'].unique()):
    mode_row = model_human_agreement_mode_df[model_human_agreement_mode_df['model'] == model].iloc[0]
    last_row = model_human_agreement_last_df[model_human_agreement_last_df['model'] == model].iloc[0]
    
    comparison_data.append({
        'Model': model,
        'Mode_Accuracy_Mean': mode_row['accuracy_mean'],
        'Mode_Accuracy_Std': mode_row['accuracy_std'],
        'Last_Accuracy_Mean': last_row['accuracy_mean'],
        'Last_Accuracy_Std': last_row['accuracy_std'],
        'Diff_Accuracy': last_row['accuracy_mean'] - mode_row['accuracy_mean'],
        'Mode_F1_Mean': mode_row['f1_score_mean'],
        'Mode_F1_Std': mode_row['f1_score_std'],
        'Last_F1_Mean': last_row['f1_score_mean'],
        'Last_F1_Std': last_row['f1_score_std'],
        'Diff_F1': last_row['f1_score_mean'] - mode_row['f1_score_mean'],
        'Mode_Poorly_Ratio': mode_row['poorly_ratio'],
        'Last_Poorly_Ratio': last_row['poorly_ratio']
    })

comparison_df = pd.DataFrame(comparison_data)
print(comparison_df.round(3))

# Save the comparison
comparison_df.to_csv('mode_vs_last_comparison.csv', index=False)
print("\nComparison table saved to 'mode_vs_last_comparison.csv'")

# Identify which method is better for each model
print("\n" + "="*80)
print("Which aggregation method performs better? (Agreement with Humans)")
print("="*80)
for _, row in comparison_df.iterrows():
    model = row['Model']
    if row['Diff_Accuracy'] > 0.01:
        print(f"{model:25s}: LAST FRAME better (Δ Accuracy: +{row['Diff_Accuracy']:.3f})")
    elif row['Diff_Accuracy'] < -0.01:
        print(f"{model:25s}: MODE better (Δ Accuracy: {row['Diff_Accuracy']:.3f})")
    else:
        print(f"{model:25s}: Similar performance (Δ Accuracy: {row['Diff_Accuracy']:.3f})")

# Overall statistics
print("\n" + "="*80)
print("Overall Statistics (Per Participant Averages)")
print("="*80)
print(f"Average Mode Accuracy: {comparison_df['Mode_Accuracy_Mean'].mean():.3f} ± {comparison_df['Mode_Accuracy_Std'].mean():.3f}")
print(f"Average Last Frame Accuracy: {comparison_df['Last_Accuracy_Mean'].mean():.3f} ± {comparison_df['Last_Accuracy_Std'].mean():.3f}")
print(f"Average Difference: {comparison_df['Diff_Accuracy'].mean():.3f}")
print(f"\nAverage Mode Poorly Ratio: {comparison_df['Mode_Poorly_Ratio'].mean():.3f}")
print(f"Average Last Frame Poorly Ratio: {comparison_df['Last_Poorly_Ratio'].mean():.3f}")
print(f"\nModels where LAST FRAME is better: {(comparison_df['Diff_Accuracy'] > 0.01).sum()}/{len(comparison_df)}")
print(f"Models where MODE is better: {(comparison_df['Diff_Accuracy'] < -0.01).sum()}/{len(comparison_df)}")
print(f"Models with similar performance: {((comparison_df['Diff_Accuracy'] >= -0.01) & (comparison_df['Diff_Accuracy'] <= 0.01)).sum()}/{len(comparison_df)}")